Add readinessProbe check to kibana dashboard

diff --git a/katalog/kibana/kibana.yml b/katalog/kibana/kibana.yml
--- a/katalog/kibana/kibana.yml
+++ b/katalog/kibana/kibana.yml
@@ -27,6 +27,27 @@ spec:
       containers:
       - name: kibana
         image: docker.elastic.co/kibana/kibana
+        readinessProbe:
+          exec:
+            command:
+              - sh
+              - -c
+              - |
+                #!/usr/bin/env bash -e
+                http () {
+                    local path="${1}"
+                    set -- -XGET -s --fail -L
+                    if [ -n "${ELASTICSEARCH_USERNAME}" ] && [ -n "${ELASTICSEARCH_PASSWORD}" ]; then
+                      set -- "$@" -u "${ELASTICSEARCH_USERNAME}:${ELASTICSEARCH_PASSWORD}"
+                    fi
+                    STATUS=$(curl --output /dev/null --write-out "%{http_code}" -k "$@" "http://localhost:5601${path}")
+                    if [[ "${STATUS}" -eq 200 ]]; then
+                      exit 0
+                    fi
+                    echo "Error: Got HTTP code ${STATUS} but expected a 200"
+                    exit 1
+                }
+                http /app/kibana
         ports:
           - containerPort: 5601
             name: http
